alter table Item
add name varchar(30);



insert into Item (price, type, name) values (508.78, 'main course', 'eu mi nulla ac');
insert into Item (price, type, name) values (734.24, 'soup', 'sit');
insert into Item (price, type, name) values (418.77, 'soup', 'vel nisl duis');
insert into Item (price, type, name) values (70.98, 'main course', 'augue aliquam erat');
insert into Item (price, type, name) values (902.83, 'desert', 'justo in blandit');
insert into Item (price, type, name) values (889.25, 'sandwich', 'quam sapien varius ut');
insert into Item (price, type, name) values (330.08, 'soup', 'ante ipsum');
insert into Item (price, type, name) values (825.3, 'desert', 'convallis tortor');
insert into Item (price, type, name) values (879.2, 'salad', 'nunc vestibulum ante ipsum');
insert into Item (price, type, name) values (370.91, 'salad', 'cum');
insert into Item (price, type, name) values (166.02, 'main course', 'sed lacus');
insert into Item (price, type, name) values (618.97, 'sandwich', 'tellus nulla ut');
insert into Item (price, type, name) values (75.08, 'sandwich', 'rutrum ac lobortis');
insert into Item (price, type, name) values (707.4, 'soup', 'vulputate justo');
insert into Item (price, type, name) values (132.41, 'desert', 'imperdiet et');
insert into Item (price, type, name) values (863.6, 'sandwich', 'rhoncus aliquet');
insert into Item (price, type, name) values (33.4, 'desert', 'nulla');
insert into Item (price, type, name) values (838.05, 'main course', 'adipiscing lorem vitae mattis');
insert into Item (price, type, name) values (548.2, 'main course', 'duis aliquam convallis nunc');
insert into Item (price, type, name) values (104.33, 'soup', 'nascetur ridiculus mus');
insert into Item (price, type, name) values (42.09, 'salad', 'et ultrices posuere cubilia');
insert into Item (price, type, name) values (831.91, 'main course', 'odio');
insert into Item (price, type, name) values (804.0, 'salad', 'quis odio consequat varius');
insert into Item (price, type, name) values (165.54, 'main course', 'aenean sit amet justo');
insert into Item (price, type, name) values (344.23, 'main course', 'donec');
insert into Item (price, type, name) values (775.06, 'sandwich', 'habitasse platea dictumst morbi');
insert into Item (price, type, name) values (962.89, 'desert', 'pharetra');
insert into Item (price, type, name) values (109.08, 'sandwich', 'justo');
insert into Item (price, type, name) values (140.24, 'sandwich', 'velit nec');
insert into Item (price, type, name) values (817.98, 'sandwich', 'integer tincidunt');
insert into Item (price, type, name) values (46.23, 'main course', 'turpis');
insert into Item (price, type, name) values (640.02, 'desert', 'ante nulla justo aliquam');
insert into Item (price, type, name) values (444.47, 'salad', 'integer tincidunt ante vel');
insert into Item (price, type, name) values (892.77, 'desert', 'aliquet pulvinar sed nisl');
insert into Item (price, type, name) values (27.21, 'salad', 'id ligula');
insert into Item (price, type, name) values (526.96, 'desert', 'consequat lectus in');
insert into Item (price, type, name) values (707.83, 'desert', 'justo');
insert into Item (price, type, name) values (356.32, 'main course', 'enim lorem');
insert into Item (price, type, name) values (132.69, 'sandwich', 'nisl nunc rhoncus');
insert into Item (price, type, name) values (712.39, 'main course', 'laoreet ut');
insert into Item (price, type, name) values (318.81, 'desert', 'a suscipit');
insert into Item (price, type, name) values (321.05, 'salad', 'lobortis est');
insert into Item (price, type, name) values (144.84, 'main course', 'tortor duis mattis');
insert into Item (price, type, name) values (631.08, 'soup', 'molestie nibh in');
insert into Item (price, type, name) values (97.55, 'salad', 'mauris morbi');
insert into Item (price, type, name) values (376.38, 'desert', 'euismod');
insert into Item (price, type, name) values (973.08, 'desert', 'magnis dis');
insert into Item (price, type, name) values (599.04, 'salad', 'pede');
insert into Item (price, type, name) values (712.9, 'soup', 'turpis');
insert into Item (price, type, name) values (198.77, 'main course', 'ultrices enim lorem ipsum');
insert into Item (price, type, name) values (410.25, 'salad', 'erat quisque erat');
insert into Item (price, type, name) values (41.98, 'salad', 'vitae quam');
insert into Item (price, type, name) values (196.6, 'soup', 'sem mauris');
insert into Item (price, type, name) values (406.84, 'sandwich', 'ut blandit non interdum');
insert into Item (price, type, name) values (912.65, 'soup', 'praesent lectus');
insert into Item (price, type, name) values (961.87, 'soup', 'sapien');
insert into Item (price, type, name) values (385.75, 'sandwich', 'nullam porttitor lacus');
insert into Item (price, type, name) values (793.48, 'sandwich', 'eu mi nulla');
insert into Item (price, type, name) values (280.24, 'desert', 'non quam nec');
insert into Item (price, type, name) values (694.07, 'salad', 'duis at velit eu');
insert into Item (price, type, name) values (830.96, 'soup', 'hendrerit');
insert into Item (price, type, name) values (135.04, 'desert', 'enim leo');
insert into Item (price, type, name) values (554.24, 'main course', 'lacinia eget tincidunt eget');
insert into Item (price, type, name) values (673.65, 'main course', 'pellentesque');
insert into Item (price, type, name) values (143.92, 'sandwich', 'orci pede');
insert into Item (price, type, name) values (768.1, 'salad', 'sapien placerat ante nulla');
insert into Item (price, type, name) values (708.53, 'soup', 'vitae mattis nibh');
insert into Item (price, type, name) values (297.01, 'main course', 'proin risus praesent');
insert into Item (price, type, name) values (937.12, 'desert', 'tempus');
insert into Item (price, type, name) values (207.97, 'soup', 'auctor');
insert into Item (price, type, name) values (687.22, 'soup', 'in');
insert into Item (price, type, name) values (142.77, 'sandwich', 'habitasse platea dictumst');
insert into Item (price, type, name) values (795.22, 'main course', 'egestas metus aenean fermentum');
insert into Item (price, type, name) values (169.67, 'salad', 'sagittis');
insert into Item (price, type, name) values (523.09, 'salad', 'quis turpis');
insert into Item (price, type, name) values (721.13, 'salad', 'placerat ante');
insert into Item (price, type, name) values (808.4, 'sandwich', 'sem duis aliquam');
insert into Item (price, type, name) values (922.69, 'desert', 'eu');
insert into Item (price, type, name) values (151.03, 'sandwich', 'nulla neque libero convallis');
insert into Item (price, type, name) values (121.94, 'salad', 'sem praesent id');
insert into Item (price, type, name) values (73.17, 'soup', 'congue vivamus');
insert into Item (price, type, name) values (868.39, 'sandwich', 'eget');
insert into Item (price, type, name) values (699.15, 'soup', 'diam id');
insert into Item (price, type, name) values (273.53, 'sandwich', 'sit amet');
insert into Item (price, type, name) values (874.88, 'salad', 'etiam vel augue');
insert into Item (price, type, name) values (404.29, 'desert', 'suspendisse ornare consequat');
insert into Item (price, type, name) values (126.31, 'sandwich', 'est et tempus');
insert into Item (price, type, name) values (224.85, 'main course', 'nulla');
insert into Item (price, type, name) values (104.93, 'salad', 'viverra eget');
insert into Item (price, type, name) values (31.75, 'desert', 'sed lacus morbi');
insert into Item (price, type, name) values (137.01, 'main course', 'fusce congue diam id');
insert into Item (price, type, name) values (106.92, 'salad', 'ipsum dolor');
insert into Item (price, type, name) values (927.29, 'desert', 'accumsan tellus nisi');
insert into Item (price, type, name) values (319.3, 'desert', 'sed accumsan');
insert into Item (price, type, name) values (323.76, 'sandwich', 'vitae');
insert into Item (price, type, name) values (83.23, 'main course', 'at dolor quis');
insert into Item (price, type, name) values (472.54, 'main course', 'sapien cursus');
insert into Item (price, type, name) values (506.55, 'sandwich', 'venenatis turpis enim blandit');
insert into Item (price, type, name) values (383.61, 'soup', 'sed interdum venenatis');
insert into Item (price, type, name) values (984.94, 'soup', 'duis');
