insert into Item (price, type, name) values (802.54, 'compound', 'sem duis aliquam convallis');
insert into Item (price, type, name) values (889.86, 'compound', 'proin');
insert into Item (price, type, name) values (462.82, 'compound', 'diam erat fermentum justo');
insert into Item (price, type, name) values (500.6, 'compound', 'eu felis fusce posuere');
insert into Item (price, type, name) values (676.24, 'compound', 'convallis nunc');
insert into Item (price, type, name) values (464.23, 'compound', 'turpis');
insert into Item (price, type, name) values (35.48, 'compound', 'laoreet ut rhoncus');
insert into Item (price, type, name) values (524.84, 'compound', 'quam fringilla rhoncus');
insert into Item (price, type, name) values (675.31, 'compound', 'pede malesuada in imperdiet');
insert into Item (price, type, name) values (428.09, 'compound', 'morbi vel lectus');
insert into Item (price, type, name) values (633.12, 'compound', 'purus eu magna vulputate');
insert into Item (price, type, name) values (183.99, 'compound', 'tortor eu');
insert into Item (price, type, name) values (140.36, 'compound', 'nam nulla integer');
insert into Item (price, type, name) values (335.57, 'compound', 'at dolor');
insert into Item (price, type, name) values (346.15, 'compound', 'quam');
insert into Item (price, type, name) values (103.4, 'compound', 'ut erat curabitur gravida');
insert into Item (price, type, name) values (376.33, 'compound', 'facilisi cras');
insert into Item (price, type, name) values (984.3, 'compound', 'at turpis donec posuere');
insert into Item (price, type, name) values (729.89, 'compound', 'ac tellus semper');
insert into Item (price, type, name) values (670.93, 'compound', 'ut erat');
insert into Item (price, type, name) values (937.07, 'compound', 'in consequat ut');
insert into Item (price, type, name) values (144.99, 'compound', 'at');
insert into Item (price, type, name) values (750.86, 'compound', 'sit amet consectetuer');
insert into Item (price, type, name) values (855.75, 'compound', 'augue a');
insert into Item (price, type, name) values (340.15, 'compound', 'auctor gravida sem praesent');
insert into Item (price, type, name) values (394.43, 'compound', 'vestibulum vestibulum');
insert into Item (price, type, name) values (468.09, 'compound', 'nulla eget eros');
insert into Item (price, type, name) values (3.72, 'compound', 'curabitur in libero');
insert into Item (price, type, name) values (588.96, 'compound', 'nisl');
insert into Item (price, type, name) values (979.86, 'compound', 'magnis dis');
insert into Item (price, type, name) values (379.02, 'compound', 'risus praesent lectus vestibulum');
insert into Item (price, type, name) values (679.73, 'compound', 'auctor sed tristique');
insert into Item (price, type, name) values (278.57, 'compound', 'in felis eu');
insert into Item (price, type, name) values (46.93, 'compound', 'nulla ac');
insert into Item (price, type, name) values (892.05, 'compound', 'diam id ornare');
insert into Item (price, type, name) values (695.63, 'compound', 'augue quam sollicitudin');
insert into Item (price, type, name) values (111.47, 'compound', 'aliquet ultrices erat tortor');
insert into Item (price, type, name) values (389.78, 'compound', 'vestibulum sed magna at');
insert into Item (price, type, name) values (919.52, 'compound', 'potenti in eleifend');
insert into Item (price, type, name) values (231.18, 'compound', 'nisl duis ac nibh');
insert into Item (price, type, name) values (840.79, 'compound', 'aliquam augue');
insert into Item (price, type, name) values (748.67, 'compound', 'lacinia aenean');
insert into Item (price, type, name) values (94.49, 'compound', 'adipiscing elit');
insert into Item (price, type, name) values (939.91, 'compound', 'donec');
insert into Item (price, type, name) values (808.35, 'compound', 'cum');
insert into Item (price, type, name) values (262.83, 'compound', 'nulla');
insert into Item (price, type, name) values (612.61, 'compound', 'ac tellus semper');
insert into Item (price, type, name) values (249.38, 'compound', 'sapien iaculis');
insert into Item (price, type, name) values (266.74, 'compound', 'nulla mollis molestie');
insert into Item (price, type, name) values (331.06, 'compound', 'orci mauris');
insert into Item (price, type, name) values (649.73, 'compound', 'duis');
insert into Item (price, type, name) values (22.27, 'compound', 'cursus vestibulum proin eu');
insert into Item (price, type, name) values (86.44, 'compound', 'in porttitor pede justo');
insert into Item (price, type, name) values (704.81, 'compound', 'in sapien iaculis congue');
insert into Item (price, type, name) values (236.43, 'compound', 'nulla suspendisse potenti');
insert into Item (price, type, name) values (951.42, 'compound', 'quam');
insert into Item (price, type, name) values (426.78, 'compound', 'eu mi');
insert into Item (price, type, name) values (513.5, 'compound', 'habitasse platea dictumst morbi');
insert into Item (price, type, name) values (467.58, 'compound', 'aliquam');
insert into Item (price, type, name) values (440.52, 'compound', 'eget');
insert into Item (price, type, name) values (854.08, 'compound', 'suspendisse ornare consequat');
insert into Item (price, type, name) values (431.46, 'compound', 'vestibulum ante ipsum primis');
insert into Item (price, type, name) values (508.78, 'compound', 'eu sapien cursus');
insert into Item (price, type, name) values (329.83, 'compound', 'nonummy integer');
insert into Item (price, type, name) values (656.78, 'compound', 'non');
insert into Item (price, type, name) values (40.46, 'compound', 'cras mi pede malesuada');
insert into Item (price, type, name) values (350.76, 'compound', 'ac');
insert into Item (price, type, name) values (154.43, 'compound', 'nulla nisl');
insert into Item (price, type, name) values (175.64, 'compound', 'fusce consequat nulla nisl');
insert into Item (price, type, name) values (517.33, 'compound', 'sapien varius ut blandit');
insert into Item (price, type, name) values (424.29, 'compound', 'orci luctus et ultrices');
insert into Item (price, type, name) values (24.62, 'compound', 'donec');
insert into Item (price, type, name) values (945.56, 'compound', 'interdum');
insert into Item (price, type, name) values (666.39, 'compound', 'vel accumsan tellus');
insert into Item (price, type, name) values (64.3, 'compound', 'proin interdum mauris');
insert into Item (price, type, name) values (467.85, 'compound', 'tincidunt');
insert into Item (price, type, name) values (871.46, 'compound', 'proin risus praesent');
insert into Item (price, type, name) values (680.61, 'compound', 'gravida sem');
insert into Item (price, type, name) values (132.82, 'compound', 'sodales');
insert into Item (price, type, name) values (852.19, 'compound', 'et tempus semper');
insert into Item (price, type, name) values (150.9, 'compound', 'aliquam');
insert into Item (price, type, name) values (364.61, 'compound', 'ante vivamus tortor duis');
insert into Item (price, type, name) values (361.21, 'compound', 'eu tincidunt in');
insert into Item (price, type, name) values (409.59, 'compound', 'luctus');
insert into Item (price, type, name) values (849.64, 'compound', 'nulla integer pede');
insert into Item (price, type, name) values (898.41, 'compound', 'mi in');
insert into Item (price, type, name) values (234.85, 'compound', 'quisque porta volutpat');
insert into Item (price, type, name) values (365.2, 'compound', 'id sapien in');
insert into Item (price, type, name) values (202.28, 'compound', 'ut erat');
insert into Item (price, type, name) values (436.74, 'compound', 'ac enim');
insert into Item (price, type, name) values (582.72, 'compound', 'volutpat sapien arcu');
insert into Item (price, type, name) values (907.88, 'compound', 'fringilla rhoncus mauris enim');
insert into Item (price, type, name) values (104.7, 'compound', 'quam a odio');
insert into Item (price, type, name) values (870.66, 'compound', 'platea dictumst etiam');
insert into Item (price, type, name) values (391.79, 'compound', 'mauris viverra diam');
insert into Item (price, type, name) values (592.43, 'compound', 'nulla dapibus dolor vel');
insert into Item (price, type, name) values (384.67, 'compound', 'ut dolor morbi');
insert into Item (price, type, name) values (273.11, 'compound', 'pede malesuada in');
insert into Item (price, type, name) values (361.34, 'compound', 'volutpat eleifend donec');
insert into Item (price, type, name) values (446.34, 'compound', 'rutrum rutrum neque aenean');
