insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('credit card', 'failed');
insert into Payment (type, status) values ('credit card', 'failed');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('bank transfer', 'refunded');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('bank transfer', 'failed');
insert into Payment (type, status) values ('debit card', 'completed');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('PayPal', 'completed');
insert into Payment (type, status) values ('credit card', 'refunded');
insert into Payment (type, status) values ('bank transfer', 'failed');
insert into Payment (type, status) values ('PayPal', 'failed');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('debit card', 'refunded');
insert into Payment (type, status) values ('bank transfer', 'refunded');
insert into Payment (type, status) values ('PayPal', 'failed');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('PayPal', 'failed');
insert into Payment (type, status) values ('debit card', 'refunded');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('PayPal', 'pending');
insert into Payment (type, status) values ('debit card', 'refunded');
insert into Payment (type, status) values ('credit card', 'failed');
insert into Payment (type, status) values ('bank transfer', 'failed');
insert into Payment (type, status) values ('PayPal', 'failed');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('debit card', 'completed');
insert into Payment (type, status) values ('debit card', 'completed');
insert into Payment (type, status) values ('credit card', 'failed');
insert into Payment (type, status) values ('credit card', 'failed');
insert into Payment (type, status) values ('credit card', 'completed');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('bank transfer', 'pending');
insert into Payment (type, status) values ('credit card', 'completed');
insert into Payment (type, status) values ('bank transfer', 'refunded');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('credit card', 'failed');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('credit card', 'completed');
insert into Payment (type, status) values ('credit card', 'completed');
insert into Payment (type, status) values ('bank transfer', 'failed');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('PayPal', 'refunded');
insert into Payment (type, status) values ('PayPal', 'completed');
insert into Payment (type, status) values ('debit card', 'refunded');
insert into Payment (type, status) values ('debit card', 'completed');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('debit card', 'completed');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('bank transfer', 'pending');
insert into Payment (type, status) values ('credit card', 'failed');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('bank transfer', 'pending');
insert into Payment (type, status) values ('PayPal', 'pending');
insert into Payment (type, status) values ('credit card', 'refunded');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('bank transfer', 'failed');
insert into Payment (type, status) values ('PayPal', 'refunded');
insert into Payment (type, status) values ('bank transfer', 'failed');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('PayPal', 'failed');
insert into Payment (type, status) values ('PayPal', 'refunded');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('debit card', 'completed');
insert into Payment (type, status) values ('bank transfer', 'pending');
insert into Payment (type, status) values ('credit card', 'failed');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('debit card', 'completed');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('PayPal', 'completed');
insert into Payment (type, status) values ('credit card', 'completed');
insert into Payment (type, status) values ('debit card', 'completed');
insert into Payment (type, status) values ('PayPal', 'failed');
insert into Payment (type, status) values ('PayPal', 'completed');
insert into Payment (type, status) values ('bank transfer', 'failed');
insert into Payment (type, status) values ('PayPal', 'refunded');
insert into Payment (type, status) values ('PayPal', 'refunded');
insert into Payment (type, status) values ('bank transfer', 'failed');
insert into Payment (type, status) values ('bank transfer', 'refunded');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('credit card', 'completed');
insert into Payment (type, status) values ('bank transfer', 'pending');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('bank transfer', 'pending');
insert into Payment (type, status) values ('bank transfer', 'refunded');
insert into Payment (type, status) values ('PayPal', 'pending');
insert into Payment (type, status) values ('credit card', 'refunded');
insert into Payment (type, status) values ('credit card', 'refunded');
insert into Payment (type, status) values ('bank transfer', 'refunded');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('credit card', 'refunded');
insert into Payment (type, status) values ('credit card', 'completed');
insert into Payment (type, status) values ('PayPal', 'failed');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('bank transfer', 'refunded');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('PayPal', 'refunded');
insert into Payment (type, status) values ('bank transfer', 'pending');
insert into Payment (type, status) values ('credit card', 'completed');
insert into Payment (type, status) values ('credit card', 'refunded');
insert into Payment (type, status) values ('credit card', 'refunded');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('PayPal', 'completed');
insert into Payment (type, status) values ('bank transfer', 'failed');
insert into Payment (type, status) values ('credit card', 'completed');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('credit card', 'failed');
insert into Payment (type, status) values ('PayPal', 'failed');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('credit card', 'refunded');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('PayPal', 'refunded');
insert into Payment (type, status) values ('PayPal', 'failed');
insert into Payment (type, status) values ('bank transfer', 'refunded');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('bank transfer', 'pending');
insert into Payment (type, status) values ('bank transfer', 'pending');
insert into Payment (type, status) values ('PayPal', 'refunded');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('bank transfer', 'refunded');
insert into Payment (type, status) values ('PayPal', 'pending');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('bank transfer', 'refunded');
insert into Payment (type, status) values ('debit card', 'refunded');
insert into Payment (type, status) values ('credit card', 'completed');
insert into Payment (type, status) values ('bank transfer', 'failed');
insert into Payment (type, status) values ('bank transfer', 'pending');
insert into Payment (type, status) values ('bank transfer', 'failed');
insert into Payment (type, status) values ('PayPal', 'completed');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('credit card', 'failed');
insert into Payment (type, status) values ('credit card', 'failed');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('PayPal', 'pending');
insert into Payment (type, status) values ('PayPal', 'pending');
insert into Payment (type, status) values ('bank transfer', 'refunded');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('bank transfer', 'refunded');
insert into Payment (type, status) values ('debit card', 'completed');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('debit card', 'completed');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('credit card', 'failed');
insert into Payment (type, status) values ('bank transfer', 'completed');
insert into Payment (type, status) values ('credit card', 'refunded');
insert into Payment (type, status) values ('bank transfer', 'failed');
insert into Payment (type, status) values ('credit card', 'refunded');
insert into Payment (type, status) values ('debit card', 'refunded');
insert into Payment (type, status) values ('PayPal', 'completed');
insert into Payment (type, status) values ('credit card', 'completed');
insert into Payment (type, status) values ('PayPal', 'completed');
insert into Payment (type, status) values ('debit card', 'failed');
insert into Payment (type, status) values ('PayPal', 'refunded');
insert into Payment (type, status) values ('bank transfer', 'failed');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('debit card', 'pending');
insert into Payment (type, status) values ('PayPal', 'pending');
insert into Payment (type, status) values ('debit card', 'refunded');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('credit card', 'pending');
insert into Payment (type, status) values ('credit card', 'completed');
insert into Payment (type, status) values ('debit card', 'completed');
insert into Payment (type, status) values ('bank transfer', 'pending');
insert into Payment (type, status) values ('credit card', 'refunded');
insert into Payment (type, status) values ('debit card', 'completed');
insert into Payment (type, status) values ('bank transfer', 'pending');
insert into Payment (type, status) values ('PayPal', 'pending');

select * from TAUser